"use client";

import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useState,
  type ReactNode,
} from "react";
import { content as defaultContent, type SiteContent } from "../content";

const STORAGE_KEY = "site-content-v1";

type Ctx = {
  content: SiteContent;
  editMode: boolean;
  setEditMode: (v: boolean) => void;
  set: (path: string, value: unknown) => void;
  addItem: (path: string, item: unknown) => void;
  removeItem: (path: string, index: number) => void;
  moveItem: (path: string, index: number, delta: number) => void;
  reset: () => void;
  exportContent: () => void;
};

const ContentContext = createContext<Ctx | null>(null);

function deepClone<T>(v: T): T {
  return JSON.parse(JSON.stringify(v));
}

function getByPath(obj: unknown, path: string): unknown {
  return path
    .split(".")
    .reduce<unknown>(
      (acc, key) =>
        acc == null ? acc : (acc as Record<string, unknown>)[key],
      obj,
    );
}

function setByPath<T>(obj: T, path: string, value: unknown): T {
  const keys = path.split(".");
  const next = deepClone(obj) as unknown as Record<string, unknown>;
  let cur: Record<string, unknown> = next;
  for (let i = 0; i < keys.length - 1; i++) {
    cur = cur[keys[i]] as Record<string, unknown>;
  }
  cur[keys[keys.length - 1]] = value;
  return next as unknown as T;
}

export function ContentProvider({ children }: { children: ReactNode }) {
  const [content, setContent] = useState<SiteContent>(defaultContent);
  const [editMode, setEditMode] = useState(false);
  const [loaded, setLoaded] = useState(false);

  useEffect(() => {
    try {
      const raw = localStorage.getItem(STORAGE_KEY);
      if (raw) {
        const parsed = JSON.parse(raw);
        // eslint-disable-next-line react-hooks/set-state-in-effect
        setContent(parsed);
      }
    } catch {
      // ignore
    }
    setLoaded(true);
  }, []);

  useEffect(() => {
    if (!loaded) return;
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(content));
    } catch {
      // ignore
    }
  }, [content, loaded]);

  const set = useCallback((path: string, value: unknown) => {
    setContent((c) => setByPath(c, path, value));
  }, []);

  const addItem = useCallback((path: string, item: unknown) => {
    setContent((c) => {
      const arr = getByPath(c, path);
      if (!Array.isArray(arr)) return c;
      return setByPath(c, path, [...arr, item]);
    });
  }, []);

  const removeItem = useCallback((path: string, index: number) => {
    setContent((c) => {
      const arr = getByPath(c, path);
      if (!Array.isArray(arr)) return c;
      return setByPath(c, path, arr.filter((_, i) => i !== index));
    });
  }, []);

  const moveItem = useCallback((path: string, index: number, delta: number) => {
    setContent((c) => {
      const arr = getByPath(c, path);
      if (!Array.isArray(arr)) return c;
      const newIndex = index + delta;
      if (newIndex < 0 || newIndex >= arr.length) return c;
      const next = [...arr];
      const [moved] = next.splice(index, 1);
      next.splice(newIndex, 0, moved);
      return setByPath(c, path, next);
    });
  }, []);

  const reset = useCallback(() => {
    setContent(deepClone(defaultContent));
  }, []);

  const exportContent = useCallback(() => {
    const body = JSON.stringify(content, null, 2);
    const ts = `// Edit this file to update every piece of copy on the site.\n// Generated by the in-browser editor.\n\nexport const content = ${body};\n\nexport type SiteContent = typeof content;\n`;
    const blob = new Blob([ts], { type: "text/typescript" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "content.ts";
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
  }, [content]);

  return (
    <ContentContext.Provider
      value={{
        content,
        editMode,
        setEditMode,
        set,
        addItem,
        removeItem,
        moveItem,
        reset,
        exportContent,
      }}
    >
      {children}
    </ContentContext.Provider>
  );
}

export function useContent() {
  const ctx = useContext(ContentContext);
  if (!ctx) throw new Error("useContent must be used inside ContentProvider");
  return ctx;
}

export function useField(path: string): string {
  const { content } = useContent();
  const value = getByPath(content, path);
  return typeof value === "string" ? value : "";
}
